apiVersion: v1
kind: Namespace
metadata:
  name: finals
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: clo835
  region: "us-east-1"
  version: "1.19"
  namespace: finals

availabilityZones: ["us-east-1a" ,"us-east-1b" ,"us-east-1c"]

cloudWatch:
  clusterLogging:
    enableTypes: ["authenticator"]
    
managedNodeGroups:
- name: nodegroup
  desiredCapacity: 2
  instanceType: t3.small
  ssh:
    enableSsm: true
