#Deploy Loadbalancer Service
apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    name: app-lb-service
spec:
  ports:
  - port: 80
    targetPort: 81
    name: http
  selector:
    app: employees
  type: LoadBalancer