apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    name: app-lb-service
spec:
  ports:
  - port: 81
    targetPort: 80
    name: http
  selector:
    app: employees
  type: LoadBalancer
