apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: final
  labels:
    app: employees
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: app
          image: 645402193523.dkr.ecr.us-east-1.amazonaws.com/finals-app:v5.0
          ports:
            - containerPort: 81
          env:
            - name: DBPWD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username            
            - name: DBPORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_PORT
            - name: DBHOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST
            - name: APP_BACKGROUND
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_BACKGROUND
            - name: GROUP_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: GROUP_NAME
