#Deploy database with EBS PVC
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 645402193523.dkr.ecr.us-east-1.amazonaws.com/mydb:1
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: mysql
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PORT
        volumeMounts:
        - name: mysql-db
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-db
        persistentVolumeClaim:
          claimName: mysql-pvc