apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-deployment-hpa
  labels:
    name: employees
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 2