#Deploy PVC for hosted path
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-hp 
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: localstorage