#Deploy secret for db password and app color
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  password: YWRtaW4=
type: kubernetes.io/basic-auth
stringData:
  color: blue