#Deploy secret for db username and password
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: final
type: Opaque
data:
  password: YWRtaW4=
type: kubernetes.io/basic-auth
stringData:
  username: root