# This is a basic workflow to help you get started with Actions

name: New Build Docker Image and Push to AWS ECR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  push:
    branches: [ "master" ]
 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
 
  # Env to use the repositories     
    env:
     ECR_REPO_PREFIX: finals
     IMAGE_TAG: v4.0
       
     
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Login to Amazon ECR with Secret Keys from CLI
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: us-east-1        
      # Runs a set of commands using the runners shell   
      - name: App build, test, tag, and push image to Amazon ECR
        env:
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # Docker build
          docker build -t $ECR_REGISTRY/$ECR_REPO_PREFIX-app:$IMAGE_TAG .
          # Unit test
          docker run -d -p 81:81 --name app $ECR_REGISTRY/$ECR_REPO_PREFIX-app:$IMAGE_TAG
          docker ps
          echo "Pause for 10 seconds to let container start"
          sleep 10
          docker push $ECR_REGISTRY/$ECR_REPO_PREFIX-app:$IMAGE_TAG
      - name: MySQL DB build, test, tag, and push image to Amazon ECR
        env:
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # Docker build
          docker build -f Dockerfile_mysql -t $ECR_REGISTRY/$ECR_REPO_PREFIX-db:$IMAGE_TAG .
          # Unit test
          docker run -d -e MYSQL_ROOT_PASSWORD=1234 --name db $ECR_REGISTRY/$ECR_REPO_PREFIX-db:$IMAGE_TAG
          docker ps
          echo "Pause for 10 seconds to let container start"
          sleep 10
          docker push $ECR_REGISTRY/$ECR_REPO_PREFIX-db:$IMAGE_TAG